### ISSUE TITLE
SlidingDrawer View Not Showing  

### ISSUE THREAD

**Issue by suman-cribello** [sayan801/SlidingDrawer#9]
In our `SlidingDrawer` Application i trying to showing SlidingDrawer layout by programmatic way .Actually we were showing 3 State `SlidingDrawer` from `XML` ,But now i trying to showing it through `Programmatic approach` .

**Comment by suman-cribello** [comment]
# What i tried

```
 SlidingDrawer SlidingDrawerObj;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_demo);

        SlidingDrawerObj=new SlidingDrawer(getApplicationContext());
```

Calling `SlidingDrawer` in Java Code instead  `XML` . 
If i call this from `XML` it works smoothly .Its strange case if i call this from `Java Class` .

**Comment by suman-cribello** [comment]
@cribello  What should i do ?

**Comment by suman-cribello** [comment]
Getting `NullPointerException` When i add `SlidingDrawerObj` 

```
 LinearLayout LL =(LinearLayout)findViewById(R.id.Testing);
        SlidingDrawerObj=new SlidingDrawer(this);
        SlidingDrawerObj.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT));
        LL.addView(SlidingDrawerObj);

```

## What error occurs

```
Process: technicise.com.demoslidingdrawerapp, PID: 14163
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
            at technicise.com.slidingdrawer3statelib.SlidingDrawer.onSizeChanged(SlidingDrawer.java:65)
            at android.view.View.sizeChange(View.java:15703)
            at android.view.View.setFrame(View.java:15676)
            at android.view.View.layout(View.java:15592)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by suman-cribello** [comment]
@sayan801  Finally this problem solved .Actually it was my fault . Commit id https://github.com/sayan801/SlidingDrawer/commit/85ebb0b607ee65277f0689742bcb6ba000d59125  Showing Slider Center text contain which generates from our Java class (Not `SlidingDrawer` Library Class).

**Comment by suman-cribello** [comment]
Now i trying to add Listview  which fetching Json data dynamically

**Comment by rupak-cribello** [comment]
ref, Set Id Programetically..
https://github.com/sayan801/LayoutWith3State/issues/1#issuecomment-139981327

**Comment by suman-cribello** [comment]
![screenshot from 2015-09-14 17 56 10](https://cloud.githubusercontent.com/assets/6313478/9849631/350cd6aa-5b0a-11e5-95bc-c357ff29b69f.png)

**Comment by suman-cribello** [comment]
Last commit id : https://github.com/sayan801/SlidingDrawer/commit/226ea098708b968cdcee3a5b817a06c3b2036c20

![screenshot_2015-09-15-15-54-51](https://cloud.githubusercontent.com/assets/6313478/9874212/5b487fe6-5bc2-11e5-90f5-9be9c282f96e.png)

**Comment by suman-cribello** [comment]
The above image (Upper portion) showing dynamic listview

**Comment by suman-cribello** [comment]
Okay .Now i trying to add Navigation Drawer functionality .https://developer.android.com/intl/zh-cn/training/implementing-navigation/nav-drawer.html
